version: '3.7'
services:

  consul-agent-1: &consul-agent
    image: hashicorp/consul:latest
    networks:
      - consul
    # -retry-joinは、指定したノードが落ちた場合に自動的に再接続するためのオプション
    # この場合は、consul-server-bootstrapが落ちた場合に再接続する
    # -clientは、クライアントのアドレスを指定するオプション
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    # -serverは、サーバーノードとして起動するためのオプション
    # サーバーノードは、クラスタのリーダーとしての役割を持つ
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      # localhost:8500でWebUIにアクセスできるようになってる
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    # -bootstrap-expectは、クラスタのノード数を指定するオプション
    # -uiは、WebUIを有効にするためのオプション
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  mongodb:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379

networks:
  consul:

volumes:
  mongodb_data: